#if true a new instance of a resource is created per request otherwise, one instance serves all requests
instance_per_request : true
port : 3434
add_thymeleaf_transformer : true
add_json_transformer : true
add_default_error_transformer : true
session_path : /
#ignored if null
session_domain:
#7 days in milliseconds
session_max_age : 604800000
session_http_only: false
#ignored if null
session_ports:
#default error template used when no template is found for the specific error message
default_error_template : error/default
#add the default injector used to inject parameters into resource methods
add_default_injector : true
#add the default filter used to locate resources (must provide de fault if false)
add_default_resource_filter : true
#if true static files will be served from template_config.
add_static_resource_filter : true
template_config :
    #if true templates are cache after first load
  cacheable : true
  #24hrs in milliseconds  (max time a template is cached for)
  cache_age_ms : 86400000
  #encoding used to read template files
  character_encoding : utf-8
  #suffix appended to all templates so that index becomes index.html
  suffix : .html
  #prefix prepended to all templates. can be directory or string...or both
  prefix : templates/
  #the resolvers determine how a template is loaded and in which order
  #if 1 then try to load templates from the class path first
  classLoader_resolver_order : 1
  #try to load templates after class path if template not found
  fileResolver_order : 2
  url_resolver_order : 3
  #when a resource returns a map, should the map's keys become template variable names?
  convert_map_responses_to_key_value_pairs : true
  #when a resource returns a pojo (not primitive, list,map,set or array)
  #should it's fields become template variables?
  convert_pojo_responses_to_key_value_pairs : true
  #thymeleaf shouldn't be configured after initialization. set this to false if you need to
  #do additional configuration, such as add a dialect etc...
  auto_initialize_thymeleaf : true
  #if true then thymeleaf's locale is set to the locale obtained from the Accept-Language http header
  #if you use multiple language files it will load one based on this locale
  determine_language_from_accept_header : true
#static files are first fetched from the class path. If not found then the path is checked on disk
files :
    #should temp uploaded files be deleted
  delete_temp_on_exit : true
  #use default system temp dir if null
  temp_directory:
  #how big are the chunks when sending a static file
  chunk_size : 8192
  #path to the directory from which static files will be served (relative or absolute)
  #bare in mind if you want to serve files from the classpath a relative path is probably best
  #if the path is relative (doesn't start with /) then a / is automatically prepended before
  #checking on disk so "public" becomes "/public"
  public_directory : public
  #if true directories in public_directory will list the files in them
  enable_directory_listing : true
  #if true when its a directory, index_file will be sent automatically if set...
  serve_index_file : true
  #the name of the default file to serve from directories
  index_file : /index.html
  #a map of file extensions to their content type.
  #any file with one of these extensions is sent with the given content-type header
  custom_mime_types :
    htm,html : text/html
    json : application/json
    xml : application/xml
    png : image/png

